language: ruby
bundler_args: --without copyright
rvm:
  - jruby-19mode
#  - jruby-20mode
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  include:
    - rvm: ruby
      script: mvn test
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
